"""empty message

Revision ID: 0cf39328d9c2
Revises: a66134bb83a6
Create Date: 2022-06-16 21:41:02.432238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cf39328d9c2'
down_revision = 'a66134bb83a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Descuento_Producto', sa.Column('fecha_inicio', sa.Integer(), nullable=False))
    op.drop_column('Descuento_Producto', 'fecha_incio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Descuento_Producto', sa.Column('fecha_incio', sa.INTEGER(), nullable=False))
    op.drop_column('Descuento_Producto', 'fecha_inicio')
    # ### end Alembic commands ###
