"""empty message

Revision ID: 0f40215f6c00
Revises: d70f433a2274
Create Date: 2022-06-12 19:00:45.434221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f40215f6c00'
down_revision = 'd70f433a2274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Comuna',
    sa.Column('id_comuna', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('id_region', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_region'], ['Region.id_region'], ),
    sa.PrimaryKeyConstraint('id_comuna')
    )
    op.create_table('Vendedor',
    sa.Column('id_vendedor', sa.Integer(), nullable=False),
    sa.Column('rut', sa.Integer(), nullable=False),
    sa.Column('dv', sa.String(length=1), nullable=False),
    sa.Column('primer_nombre', sa.String(length=250), nullable=False),
    sa.Column('segundo_nombre', sa.String(length=250), nullable=True),
    sa.Column('primer_apellido', sa.String(length=250), nullable=False),
    sa.Column('segundo_apellido', sa.String(length=250), nullable=True),
    sa.Column('direccion', sa.String(length=250), nullable=False),
    sa.Column('fono', sa.Integer(), nullable=False),
    sa.Column('correo', sa.String(length=250), nullable=False),
    sa.Column('estado', sa.String(length=1), nullable=False),
    sa.Column('id_comuna', sa.Integer(), nullable=True),
    sa.Column('id_region', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_comuna'], ['Comuna.id_comuna'], ),
    sa.ForeignKeyConstraint(['id_region'], ['Region.id_region'], ),
    sa.PrimaryKeyConstraint('id_vendedor')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Vendedor')
    op.drop_table('Comuna')
    # ### end Alembic commands ###
