"""empty message

Revision ID: 1de6119cb4e2
Revises: 6a6c09277cde
Create Date: 2022-06-16 23:34:01.890571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1de6119cb4e2'
down_revision = '6a6c09277cde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Despacho',
    sa.Column('id_despacho', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(length=250), nullable=False),
    sa.Column('fecha_entrega', sa.Integer(), nullable=True),
    sa.Column('hora_entrega', sa.Integer(), nullable=True),
    sa.Column('rut_recibe', sa.Integer(), nullable=True),
    sa.Column('nombre_recibe', sa.Integer(), nullable=True),
    sa.Column('estado_despacho', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('comuna_ida', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_despacho')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Despacho')
    # ### end Alembic commands ###
