"""empty message

Revision ID: 2a420e8ebb72
Revises: ddf8d2205153
Create Date: 2022-06-15 21:31:48.422486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a420e8ebb72'
down_revision = 'ddf8d2205153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Region',
    sa.Column('id_region', sa.Integer(), nullable=False),
    sa.Column('nombre_region', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id_region')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Region')
    # ### end Alembic commands ###
