"""empty message

Revision ID: 3e1e6c600522
Revises: 
Create Date: 2022-06-12 18:36:50.788197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e1e6c600522'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Descuento',
    sa.Column('id_descuento', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('fecha', sa.Integer(), nullable=False),
    sa.Column('porcentaje', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_descuento')
    )
    op.create_table('Region',
    sa.Column('id_region', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id_region')
    )
    op.create_table('Usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rut', sa.Integer(), nullable=False),
    sa.Column('dv', sa.String(length=1), nullable=False),
    sa.Column('primer_nombre', sa.String(length=250), nullable=False),
    sa.Column('segundo_nombre', sa.String(length=250), nullable=True),
    sa.Column('primer_apellido', sa.String(length=250), nullable=False),
    sa.Column('segundo_apellido', sa.String(length=250), nullable=True),
    sa.Column('direccion', sa.String(length=250), nullable=False),
    sa.Column('fono', sa.Integer(), nullable=False),
    sa.Column('correo', sa.String(length=250), nullable=False),
    sa.Column('estado', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Suscripcion',
    sa.Column('id_suscripcion', sa.Integer(), nullable=False),
    sa.Column('fecha_inicico', sa.Integer(), nullable=False),
    sa.Column('fecha_termino', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['Usuario.id'], ),
    sa.PrimaryKeyConstraint('id_suscripcion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Suscripcion')
    op.drop_table('Usuario')
    op.drop_table('Region')
    op.drop_table('Descuento')
    # ### end Alembic commands ###
