"""empty message

Revision ID: 5bd72d6c489d
Revises: b7df7fe0c3ba
Create Date: 2022-06-30 00:20:16.125067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd72d6c489d'
down_revision = 'b7df7fe0c3ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cliente', sa.Column('clave', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Cliente', 'clave')
    # ### end Alembic commands ###
