"""empty message

Revision ID: 698bab344b48
Revises: 02548ebbb62e
Create Date: 2022-07-08 20:33:06.098072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698bab344b48'
down_revision = '02548ebbb62e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Cliente', 'clave')
    op.drop_column('Cliente', 'region_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cliente', sa.Column('region_id', sa.INTEGER(), nullable=False))
    op.add_column('Cliente', sa.Column('clave', sa.VARCHAR(length=15), nullable=True))
    # ### end Alembic commands ###
