"""empty message

Revision ID: 9dba365d6979
Revises: 
Create Date: 2022-06-15 19:44:37.118992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dba365d6979'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Descuento',
    sa.Column('id_descuento', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('fecha', sa.Integer(), nullable=False),
    sa.Column('porcentaje', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_descuento')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Descuento')
    # ### end Alembic commands ###
