"""empty message

Revision ID: a1f9029800b1
Revises: 698bab344b48
Create Date: 2022-07-08 20:49:19.878994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1f9029800b1'
down_revision = '698bab344b48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venta', 'despacho_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venta', 'despacho_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
