"""empty message

Revision ID: b7df7fe0c3ba
Revises: 3e57a8fd70bf
Create Date: 2022-06-30 00:17:09.368581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7df7fe0c3ba'
down_revision = '3e57a8fd70bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Cliente', 'clave')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cliente', sa.Column('clave', sa.VARCHAR(length=15), nullable=False))
    # ### end Alembic commands ###
