"""empty message

Revision ID: ddf8d2205153
Revises: 9dba365d6979
Create Date: 2022-06-15 20:53:14.753480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf8d2205153'
down_revision = '9dba365d6979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Producto',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=250), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('valor_venta', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.Column('imagen', sa.BLOB(), nullable=True),
    sa.Column('estado', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id_producto')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Producto')
    # ### end Alembic commands ###
