"""empty message

Revision ID: e53b2f9bae4e
Revises: 5bd72d6c489d
Create Date: 2022-06-30 01:03:16.176216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e53b2f9bae4e'
down_revision = '5bd72d6c489d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Despacho', sa.Column('comuna_id', sa.Integer(), nullable=False))
    op.drop_column('Despacho', 'comuna_ida')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Despacho', sa.Column('comuna_ida', sa.INTEGER(), nullable=False))
    op.drop_column('Despacho', 'comuna_id')
    # ### end Alembic commands ###
