"""empty message

Revision ID: ecab8d135a62
Revises: 9a97b166248b
Create Date: 2022-06-16 22:59:17.379392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecab8d135a62'
down_revision = '9a97b166248b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Suscripcion',
    sa.Column('id_suscripcion', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Integer(), nullable=False),
    sa.Column('fecha_termino', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_suscripcion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Suscripcion')
    # ### end Alembic commands ###
